version: '3'
services:
  shopping-cart-app:
    container_name: shopping-cart
    image: shopping-cart:latest
    network_mode: host
    depends_on:
      - mongo
  
  mongo:
    container_name: mongoDB
    image: mongo:latest
    network_mode: host
    restart: unless-stopped