version: '3'
services:
  shopping-cart-app:
    container_name: shopping-cart
    image: shopping-cart:latest
    ports:
      - 3000:3000
      - 3001:3001
  
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017